MCOP-55 - don't treat empty results as though they're not empty
Array#max on an empty array will return nil, which then will cause
the error:

    undefined method `+' for nil:NilClass (NoMethodError) from /usr/libexec/mcollective/mcollective/application/service.rb:70:in `main'

Here we gate the results processing on getting a populated results set.